#!/usr/bin/env bash
# print subdomains

if [ -z "$2" ]
then
      DOMAIN=$1
      IPW=$(dig +short "www."$DOMAIN | tail -n1)
      echo "the subdomain www is a A record and points to $IPW"
      IPL=$(dig +short "lb-01."$DOMAIN | tail -n1)
      echo "the subdomain lb-01 is a A record and points to $IPL"
      IPW1=$(dig +short "web-01."$DOMAIN | tail -n1)
      echo "the subdomain web-01 is a A record and points to $IPW1"
      IPW2=$(dig +short "web-02."$DOMAIN | tail -n1)
      echo "the subdomain web-02 is a A record and points to $IPW2"
else
      PUNTO="."
      DOMAIN=$2$PUNTO$1
      IP=$(dig +short $DOMAIN | tail -n1)
      echo "the subdomain $2 is a A record and points to $IP"
fi
