#!/usr/bin/env bash
# advanced
echo "$$" /var/run/holbertonscript.pid
for ((i = 0; i < 10;))
do
echo To infinity and beyond
sleep 2
trap 'echo I hate the kill command; rm /var/run/holbertonscript.pid; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT
done
