#!/usr/bin/env bash
# nginx user configuration
sudo sed -1 "s/80/8080/g" /etc/nginx/sites-available/default
chmod 777 /etc/nginx/nginx.conf
sudo sed -i '2i\\nuser nginx;' /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
