#!/usr/bin/env bash
# nginx user configuration
sudo pkill -o apache2
chmod 777 /etc/nginx/nginx.conf
sudo sed -i '2i\\n user nginx;' /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
su nginx -c 'service nginx restart'
